apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eee-dog-ing
  namespace: static-sites
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      return 301 https://shorturl.yimian.xyz/s/index.php?s=$request_uri;
spec:
  ingressClassName: nginx
  rules:
  - host: eee.dog
  tls:
    - hosts:
        - eee.dog
      secretName: eee-dog-tls
