kind: Service
apiVersion: v1
metadata:
  name: www-eee-dog-svc
  namespace: static-sites
spec:
  type: ExternalName
  externalName: iotcat.github.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www-eee-dog-ing
  namespace: static-sites
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: iotcat.github.io
    nginx.ingress.kubernetes.io/rewrite-target: /EEE.DOG-public/$1
spec:
  ingressClassName: nginx
  rules:
  - host: www.eee.dog
    http:
      paths:
        - path: /(.*)
          pathType: Prefix
          backend:
            service:
              name: www-eee-dog-svc
              port: 
                number: 443
  tls:
    - hosts:
        - www.eee.dog
      secretName: eee-dog-tls
