apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eee-dog-cert
  namespace: static-sites
spec:
  secretName: eee-dog-tls
  issuerRef:
    name: dnspod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - "eee.dog"
  - "*.eee.dog"
