apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: yimian-xyz-cert
  namespace: static-sites
spec:
  secretName: yimian-xyz-tls
  issuerRef:
    name: dnspod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - "yimian.xyz"
  - "*.yimian.xyz"
